### ISSUE TITLE
Using middleware

### ISSUE THREAD

**Issue by lmcardle** [staticdeploy/mock-server#16]
Is there a current way to use Express middleware? For example, `.use(express.static(resolve(options.root, '../dist/scripts')))`? This is just an example, but curious how to add arbitrary middleware.

**Comment by lmcardle** [comment]
Assuming there is no other way to achieve this currently, here is one way to achieve it: https://github.com/staticdeploy/mock-server/pull/17

**Comment by pscanf** [comment]
Closed by #17 🙂
